// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4Tff5KYliw_aA-3wVn34EUNluqvxZug',
    appId: '1:991746791561:android:a09ed03e601fa93cb04e58',
    messagingSenderId: '991746791561',
    projectId: 'hrandhi-cmsc5303-mobileapps',
    storageBucket: 'hrandhi-cmsc5303-mobileapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5KgBg4_MPFjg3fNVy3AqSB3XKWvYJxc',
    appId: '1:991746791561:ios:1f4a31ab0deb7f5cb04e58',
    messagingSenderId: '991746791561',
    projectId: 'hrandhi-cmsc5303-mobileapps',
    storageBucket: 'hrandhi-cmsc5303-mobileapps.appspot.com',
    iosClientId: '991746791561-svphlsd8l0j01kv61cqaqjds47d5uc30.apps.googleusercontent.com',
    iosBundleId: 'edu.uco.hrandhi.cmsc5303.lesson3',
  );
}
